import { ModuleOptions } from './module'

export const generateConfigContents = ({ plugins, defaultLocale, locales, defaultTimeZone }: ModuleOptions) => {
  const shouldSetDefaultLocale = !!defaultLocale
  const shouldSetDefaultTimeZone = !!defaultTimeZone
  const shouldImportDayJs = !!plugins.length || shouldSetDefaultLocale || shouldSetDefaultTimeZone

  return `// Generated by @nuxtjs/dayjs
${shouldImportDayJs ? "import dayjs from 'dayjs'" : ''}
${locales.map(l => `import 'dayjs/locale/${l}'`).join('\n')}
${shouldSetDefaultLocale ? `dayjs.locale('${defaultLocale}')` : ''}
${plugins.map((p) => {
  const _p = renamePlugin(p)
  return `import ${_p} from 'dayjs/plugin/${p}.js'\ndayjs.extend(${_p})`
}).join('\n')}
${shouldSetDefaultTimeZone ? `dayjs.tz.setDefault('${defaultTimeZone}')` : ''}
`
}

function renamePlugin (plugin: string) {
  return plugin.replace(/[^A-Za-z]/g, '_')
}
